### Decision tree classifier

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
 
# load data
data=pd.read_csv("SaYoPillow.csv")

data.head()
data.rename(columns = {'sr':'snoring rate', 'rr':'respiration rate',
                        't':'body temperature', 'lm':'limb movement', 
                        'bo':'blood oxygen', 'rem':'eye movement', 
                        'sr.1':'sleeping hours','hr':'heart rate', 
                        'sl':'stress level'}, inplace = True)


X = np.array(data.iloc[:, :-1])
y = np.array(data.iloc[:, -1])
y= y.reshape((len(y),1))
 
# dividing X, y into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)
 


In [3]:
# training a DescisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, dtree_predictions)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  1 29  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0 37  0]]


### SVM (Support vector machine) classifier

In [4]:
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, np.ravel(y_train))
svm_predictions = svm_model_linear.predict(X_test)
 
# model accuracy for X_test 
accuracy = svm_model_linear.score(X_test, y_test)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, svm_predictions)
print(cm)

[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


## KNN (k-nearest neighbors) classifier

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, np.ravel(y_train))
 
# accuracy on X_test
accuracy = knn.score(X_test, y_test)
print(accuracy)
 
# creating a confusion matrix
knn_predictions = knn.predict(X_test)
cm = confusion_matrix(y_test, knn_predictions)
print(cm)

1.0
[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]


## Naive Bayes classifier

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, np.ravel(y_train))
gnb_predictions = gnb.predict(X_test)
 
# accuracy on X_test
accuracy = gnb.score(X_test, y_test)
print(accuracy)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, gnb_predictions)

print(cm)

1.0
[[36  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 37]]
